<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<AssemblyName>PDF_Editor</AssemblyName>
		<AssemblyTitle>PDF Editor</AssemblyTitle>
		<ApplicationIcon>Source/Resources/Icon.ico</ApplicationIcon>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
		<PublishSingleFile>true</PublishSingleFile>
		<PublishReferencesSymbols>false</PublishReferencesSymbols>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	</PropertyGroup>
	<ItemGroup>
		<ApplicationDefinition Include="Source\Styles\App.xaml" />
		<Content Include="pdfium.dll" CopyToOutputDirectory="Always" CopyToPublishDirectory="Always" ExcludeFromSingleFile="true" />
		<PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
		<PackageReference Include="PDFiumDotNET.WpfControls" Version="1.0.4" />
		<PackageReference Include="PDFsharp" Version="6.2.4" />
		<PackageReference Include="PDFtoImage" Version="5.3.0" />
	</ItemGroup>
	<Target Name="RemovePdbFilesFromPublish" AfterTargets="Publish">
		<ItemGroup>
			<PdbFiles Include="$(PublishDir)**\*.pdb" />
		</ItemGroup>
		<Delete Files="@(PdbFiles)" />
	</Target>
</Project>